const DAY_LABELS={"2026-09-28":"Понедельник · 28 сентября","2026-09-29":"Вторник · 29 сентября"};
const TYPE_LABELS={registration:"Организация",speech:"Открытие",plenary:"Доклад",session:"Сессия",break:"Перерыв",parent:"Голос родителя",masterclass:"Мастер-класс",excursion:"Экскурсия",roundtable:"Круглый стол",closing:"Итоги"};
const events=[...(window.DAY1_EVENTS||[]),...(window.DAY2_EVENTS||[])];
let selectedDay="2026-09-28",currentView="schedule",activeTopic=null,favorites=loadFavorites();
const scheduleList=document.getElementById("schedule-list"),scheduleKicker=document.getElementById("schedule-kicker"),searchInput=document.getElementById("search-input"),speakersList=document.getElementById("speakers-list"),topicsList=document.getElementById("topics-list"),topicResults=document.getElementById("topic-results"),favoritesList=document.getElementById("favorites-list"),favoritesHint=document.getElementById("favorites-hint"),speakerDialog=document.getElementById("speaker-dialog"),speakerDialogContent=document.getElementById("speaker-dialog-content");
function loadFavorites(){try{const v=JSON.parse(localStorage.getItem("kirov-earlyhelp-favorites")||"[]");return new Set(Array.isArray(v)?v:[])}catch{return new Set()}}
function saveFavorites(){localStorage.setItem("kirov-earlyhelp-favorites",JSON.stringify([...favorites]))}
function timeLabel(e){return e.end?`${e.start}–${e.end}`:e.start}
function eventTimestamp(e,k){return new Date(`${e.day}T${e[k]||e.start}:00+03:00`).getTime()}
function isCurrent(e){const n=Date.now();return n>=eventTimestamp(e,"start")&&n<eventTimestamp(e,"end")}
function matchesSearch(e,q){if(!q)return true;return [e.title,e.speaker,e.speakerRole,e.description,e.venue,...(e.tags||[])].filter(Boolean).join(" ").toLocaleLowerCase("ru").includes(q.toLocaleLowerCase("ru"))}
function badgeForType(t){const c=t==="masterclass"?" badge--yellow":t==="excursion"||t==="roundtable"?" badge--green":"";return `<span class="badge${c}">${TYPE_LABELS[t]||t}</span>`}
function eventCard(e,{showDay=false,hideTime=false}={}){const c=["schedule-card"];if(e.type==="break"||e.type==="registration")c.push("schedule-card--break");if(e.type==="excursion"||e.type==="roundtable")c.push("schedule-card--place");if(hideTime)c.push("schedule-card--parallel");if(isCurrent(e))c.push("is-now");const allowed=e.favorite!==false;const fav=allowed?`<button class="favorite-button${favorites.has(e.id)?" is-favorite":""}" type="button" data-favorite="${e.id}" aria-label="${favorites.has(e.id)?"Убрать из моей программы":"Добавить в мою программу"}" aria-pressed="${favorites.has(e.id)}">${favorites.has(e.id)?"★":"☆"}</button>`:`<span></span>`;return `<article class="${c.join(" ")}" data-event-id="${e.id}">${hideTime?"":`<div class="schedule-card__time">${timeLabel(e)}</div>`}<div class="schedule-card__body"><div class="schedule-card__meta">${showDay?`<span class="badge">${e.day==="2026-09-28"?"28 сен":"29 сен"}</span>`:""}${badgeForType(e.type)}</div><h3>${e.title}</h3>${e.speaker?`<p class="schedule-card__speaker">${e.speaker}</p>`:""}${e.description?`<p class="schedule-card__description">${e.description}</p>`:""}${e.venue?`<p class="schedule-card__venue">📍 ${e.venue}</p>`:""}</div>${fav}</article>`}
function renderSchedule(){const q=searchInput.value.trim();scheduleKicker.textContent=DAY_LABELS[selectedDay];const dayEvents=events.filter(e=>e.day===selectedDay&&matchesSearch(e,q));if(!dayEvents.length){scheduleList.innerHTML='<div class="empty-state">Ничего не найдено. Попробуйте другое слово.</div>';return}const done=new Set(),html=[];dayEvents.forEach(e=>{if(!e.parallelGroup){html.push(eventCard(e));return}if(done.has(e.parallelGroup))return;done.add(e.parallelGroup);const g=dayEvents.filter(x=>x.parallelGroup===e.parallelGroup),total=events.filter(x=>x.day===selectedDay&&x.parallelGroup===e.parallelGroup).length;html.push(`<div class="parallel-group"><div class="parallel-group__header"><strong>${timeLabel(e)}</strong><small>${g.length===total?`${total} мастер-класса одновременно`:`Показано ${g.length} из ${total}`}</small></div>${g.map(x=>eventCard(x,{hideTime:true})).join("")}</div>`)});scheduleList.innerHTML=html.join("");bindFavoriteButtons(scheduleList)}
function getSpeakerMap(){const m=new Map();events.filter(e=>e.speaker).forEach(e=>{if(!m.has(e.speaker))m.set(e.speaker,{name:e.speaker,role:e.speakerRole||"",talks:[]});const s=m.get(e.speaker);if((e.speakerRole||"").length>s.role.length)s.role=e.speakerRole||s.role;s.talks.push(e)});return [...m.values()].sort((a,b)=>a.name.localeCompare(b.name,"ru"))}
function renderSpeakers(){const q=searchInput.value.trim().toLocaleLowerCase("ru"),s=getSpeakerMap().filter(x=>!q||[x.name,x.role,...x.talks.map(t=>t.title)].join(" ").toLocaleLowerCase("ru").includes(q));speakersList.innerHTML=s.length?s.map(x=>`<button class="speaker-card" type="button" data-speaker="${x.name}"><div class="speaker-card__top"><div><h3>${x.name}</h3><p>${x.role}</p></div><span class="speaker-card__count" aria-label="Количество выступлений">${x.talks.length}</span></div></button>`).join(""):'<div class="empty-state">Спикеры по этому запросу не найдены.</div>';speakersList.querySelectorAll("[data-speaker]").forEach(b=>b.addEventListener("click",()=>openSpeaker(b.dataset.speaker)))}
function openSpeaker(name){const s=getSpeakerMap().find(x=>x.name===name);if(!s)return;speakerDialogContent.innerHTML=`<span class="section-kicker">Спикер</span><h2>${s.name}</h2><p class="speaker-dialog__role">${s.role}</p><div class="speaker-dialog__talks">${s.talks.map(t=>`<div class="speaker-dialog__talk"><small>${t.day==="2026-09-28"?"28 сентября":"29 сентября"} · ${timeLabel(t)}</small><strong>${t.title}</strong></div>`).join("")}</div>`;speakerDialog.showModal()}
function topicCounts(){const m=new Map();events.forEach(e=>(e.tags||[]).forEach(t=>m.set(t,(m.get(t)||0)+1)));return [...m.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],"ru"))}
function renderTopics(){topicsList.innerHTML=topicCounts().map(([t,n])=>`<button class="topic-chip${activeTopic===t?" is-active":""}" type="button" data-topic="${t}">${t} · ${n}</button>`).join("");topicsList.querySelectorAll("[data-topic]").forEach(b=>b.addEventListener("click",()=>{activeTopic=activeTopic===b.dataset.topic?null:b.dataset.topic;renderTopics()}));renderTopicResults()}
function renderTopicResults(){if(!activeTopic){topicResults.innerHTML='<div class="empty-state">Выберите тему — здесь появятся все связанные события программы.</div>';return}const related=events.filter(e=>(e.tags||[]).includes(activeTopic));topicResults.innerHTML=related.map(e=>eventCard(e,{showDay:true})).join("");bindFavoriteButtons(topicResults)}
function renderFavorites(){const s=events.filter(e=>favorites.has(e.id));favoritesHint.hidden=s.length>0;favoritesList.innerHTML=s.length?s.map(e=>eventCard(e,{showDay:true})).join(""):'<div class="empty-state">Пока ничего не сохранено. Добавляйте события звёздочкой ☆.</div>';bindFavoriteButtons(favoritesList)}
function bindFavoriteButtons(root){root.querySelectorAll("[data-favorite]").forEach(b=>b.addEventListener("click",()=>toggleFavorite(b.dataset.favorite)))}
function toggleFavorite(id){favorites.has(id)?favorites.delete(id):favorites.add(id);saveFavorites();renderSchedule();renderFavorites();if(activeTopic)renderTopicResults()}
function setDay(day){selectedDay=day;document.querySelectorAll("[data-day]").forEach(b=>{const a=b.dataset.day===day;b.classList.toggle("is-active",a);b.setAttribute("aria-selected",String(a))});renderSchedule()}
function setView(view,scroll=true){currentView=view;document.querySelectorAll("[data-view]").forEach(s=>s.hidden=s.dataset.view!==view);document.querySelectorAll(".bottom-nav__item").forEach(b=>b.classList.toggle("is-active",b.dataset.viewTarget===view));if(view==="schedule")renderSchedule();if(view==="speakers")renderSpeakers();if(view==="topics")renderTopics();if(view==="favorites")renderFavorites();if(scroll)document.querySelector(".app-shell").scrollIntoView({behavior:"smooth",block:"start"})}
function jumpToCurrent(){const active=events.find(e=>e.day===selectedDay&&isCurrent(e)),b=document.getElementById("now-button");if(!active){const o=b.textContent;b.textContent="Сейчас по программе пауза";setTimeout(()=>b.textContent=o,1800);return}document.querySelector(`[data-event-id="${active.id}"]`)?.scrollIntoView({behavior:"smooth",block:"center"})}
document.querySelectorAll("[data-day]").forEach(b=>b.addEventListener("click",()=>setDay(b.dataset.day)));
document.querySelectorAll("[data-view-target]").forEach(b=>b.addEventListener("click",()=>setView(b.dataset.viewTarget)));
document.querySelectorAll("[data-jump-day]").forEach(b=>b.addEventListener("click",()=>{setDay(b.dataset.jumpDay);setView("schedule")}));
searchInput.addEventListener("input",()=>{if(currentView==="schedule")renderSchedule();if(currentView==="speakers")renderSpeakers()});
document.getElementById("now-button").addEventListener("click",jumpToCurrent);document.querySelector(".dialog-close").addEventListener("click",()=>speakerDialog.close());speakerDialog.addEventListener("click",e=>{if(e.target===speakerDialog)speakerDialog.close()});
renderSchedule();renderSpeakers();renderTopics();renderFavorites();
